# Generated by Django 5.1.3 on 2025-01-06 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='areas.area', verbose_name='Upper administrative subdivision')),
            ],
            options={
                'verbose_name': 'Provincial City District',
                'verbose_name_plural': 'Provincial City District',
                'db_table': 'tb_areas',
            },
        ),
    ]
